# Generated by Django 3.2.25 on 2026-01-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0002_blacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneyPotHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='user-agent')),
                ('path', models.TextField(blank=True, null=True, verbose_name='path')),
                ('session_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='session key')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
            ],
            options={
                'verbose_name': 'honeypot hit',
                'verbose_name_plural': 'honeypot hits',
                'ordering': ('-created_date',),
            },
        ),
    ]
